//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodicalSupportDisciplines.BLL.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthService_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthService_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MethodicalSupportDisciplines.BLL.Resources.Services.AuthService.en", typeof(AuthService_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role of the teacher is successfully given to the user.
        /// </summary>
        internal static string AssignStudentSuccess {
            get {
                return ResourceManager.GetString("AssignStudentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while trying to assign a guest the role of student.
        /// </summary>
        internal static string AssignStudentUnknownError {
            get {
                return ResourceManager.GetString("AssignStudentUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role of the teacher is successfully given to the user.
        /// </summary>
        internal static string AssignTeacherSuccess {
            get {
                return ResourceManager.GetString("AssignTeacherSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while trying to assign a guest the role of teacher.
        /// </summary>
        internal static string AssignTeacherUnknownError {
            get {
                return ResourceManager.GetString("AssignTeacherUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before logging in, go to your email and confirm your identity.
        /// </summary>
        internal static string ConfirmEmailError {
            get {
                return ResourceManager.GetString("ConfirmEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to confirm your email.
        /// </summary>
        internal static string ConfirmEmailUnknownError {
            get {
                return ResourceManager.GetString("ConfirmEmailUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while trying to confirm Email.
        /// </summary>
        internal static string ConfirmError {
            get {
                return ResourceManager.GetString("ConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been successfully verified.
        /// </summary>
        internal static string ConfirmSuccess {
            get {
                return ResourceManager.GetString("ConfirmSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get &apos;guest&apos; user role.
        /// </summary>
        internal static string ErrorGetRole {
            get {
                return ResourceManager.GetString("ErrorGetRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to create a new user.
        /// </summary>
        internal static string ErrorTryCreateAccount {
            get {
                return ResourceManager.GetString("ErrorTryCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting a user.
        /// </summary>
        internal static string GetUserError {
            get {
                return ResourceManager.GetString("GetUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has successfully logged in.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while trying to log the user in.
        /// </summary>
        internal static string LoginUnknownError {
            get {
                return ResourceManager.GetString("LoginUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method received an incorrect value, possibly null.
        /// </summary>
        internal static string MethodGetIncorrectData {
            get {
                return ResourceManager.GetString("MethodGetIncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user with the given ID was found.
        /// </summary>
        internal static string NoUserWithId {
            get {
                return ResourceManager.GetString("NoUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of the user with the specified Email is incorrect.
        /// </summary>
        internal static string PasswordForEmailIncorrect {
            get {
                return ResourceManager.GetString("PasswordForEmailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword, ConfirmNewPassword fields do not match.
        /// </summary>
        internal static string PasswordsMatchError {
            get {
                return ResourceManager.GetString("PasswordsMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password change request was successfully sent to the specified e-mail address.
        /// </summary>
        internal static string RemindSuccess {
            get {
                return ResourceManager.GetString("RemindSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while trying to send an email to change the password.
        /// </summary>
        internal static string RemindUnknownError {
            get {
                return ResourceManager.GetString("RemindUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to change the password.
        /// </summary>
        internal static string ResetPasswordError {
            get {
                return ResourceManager.GetString("ResetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        internal static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while trying to change the password.
        /// </summary>
        internal static string ResetPasswordUnknownError {
            get {
                return ResourceManager.GetString("ResetPasswordUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while trying to register a new user.
        /// </summary>
        internal static string UnknownRegisterError {
            get {
                return ResourceManager.GetString("UnknownRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the specified e-mail address was not found.
        /// </summary>
        internal static string UserWithEmailNotFound {
            get {
                return ResourceManager.GetString("UserWithEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have an Email.
        /// </summary>
        internal static string UserWithoutEmail {
            get {
                return ResourceManager.GetString("UserWithoutEmail", resourceCulture);
            }
        }
    }
}
