//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodicalSupportDisciplines.MVC.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MethodicalSupportDisciplines.MVC.Resources.Views.Home.Index.uk", typeof(Index_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дана роль призначена для загального управління всіми процесами системи. Ви маєте доступ до управління користувачами, їх видалення, можете надсилати їм запити на зміну їх даних, якщо виявили у таблиці несправності. Також, маєте доступ до управління групами курсів, їх формалізації та доступом до всіх навчальних матеріалів, які викладачі надають студентам. .
        /// </summary>
        internal static string AdminMainString {
            get {
                return ResourceManager.GetString("AdminMainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітаємо Вас у системі «Методичне забезпечення дисциплін».
        /// </summary>
        internal static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З повагою, Команда Розробників даного сайту.
        /// </summary>
        internal static string EndSubtitle {
            get {
                return ResourceManager.GetString("EndSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка ідентифікації ролі. Можливо ви увійшли у тестовий акаунт, або система дала збій..
        /// </summary>
        internal static string ExceptionRoleString {
            get {
                return ResourceManager.GetString("ExceptionRoleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даний сайт призначения для автоматизація веденя вчителями методичних забезпечень (видання підручників, файлів, сайтів), контролювання їх проходження, взаємодії між вчителями та студентами та ведення результатів поточного контролю..
        /// </summary>
        internal static string GenericInformation {
            get {
                return ResourceManager.GetString("GenericInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви маєте роль гостя, для подальшого використання системи, вам потрібно чекати, поки адмін надасть вам інакшу роль - студента або вчителя..
        /// </summary>
        internal static string GuestMainString {
            get {
                return ResourceManager.GetString("GuestMainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо виникли питання щодо навчання або роботи системи, пишіть на електронну пошту розробників: saibl.og203@gmail.com.
        /// </summary>
        internal static string HelpInformation {
            get {
                return ResourceManager.GetString("HelpInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шановні відвідувачі системи!.
        /// </summary>
        internal static string MainSubtitle {
            get {
                return ResourceManager.GetString("MainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дана роль призначена для .
        /// </summary>
        internal static string StudentMainString {
            get {
                return ResourceManager.GetString("StudentMainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дана роль призначена для .
        /// </summary>
        internal static string TeacherMainString {
            get {
                return ResourceManager.GetString("TeacherMainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна сторінка.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
