//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MethodicalSupportDisciplines.MVC.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MethodicalSupportDisciplines.MVC.Resources.Views.Home.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is intended for the overall management of all system processes. You have access to managing users, deleting them, and can send them requests to change their data if you find faults in the table. Also, you have access to managing course groups, their formalization, and access to all the training materials that teachers provide to students. .
        /// </summary>
        internal static string AdminMainString {
            get {
                return ResourceManager.GetString("AdminMainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the &quot;Methodological support of disciplines&quot; system.
        /// </summary>
        internal static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely, the Development Team of this site.
        /// </summary>
        internal static string EndSubtitle {
            get {
                return ResourceManager.GetString("EndSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role identification error. You may be logged in to a test account or the system has failed..
        /// </summary>
        internal static string ExceptionRoleString {
            get {
                return ResourceManager.GetString("ExceptionRoleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is designed to automate the management of teaching materials (textbooks, files, websites) by teachers, monitor their progress, interactions between teachers and students, and maintain the results of ongoing monitoring..
        /// </summary>
        internal static string GenericInformation {
            get {
                return ResourceManager.GetString("GenericInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the role of a guest, and to use the system further, you need to wait until the administrator gives you another role - student or teacher..
        /// </summary>
        internal static string GuestMainString {
            get {
                return ResourceManager.GetString("GuestMainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions about training or the system&apos;s operation, please contact the developers at &lt;a href=&quot;mailto: saibl.og203@gmail.com&quot;&gt;saibl.og203@gmail.com&lt;/a&gt;..
        /// </summary>
        internal static string HelpInformation {
            get {
                return ResourceManager.GetString("HelpInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear visitors of the system!.
        /// </summary>
        internal static string MainSubtitle {
            get {
                return ResourceManager.GetString("MainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is intended for .
        /// </summary>
        internal static string StudentMainString {
            get {
                return ResourceManager.GetString("StudentMainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is intended for .
        /// </summary>
        internal static string TeacherMainString {
            get {
                return ResourceManager.GetString("TeacherMainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
